### ISSUE TITLE
Global surrounding.json definitions

### ISSUE THREAD

**Issue by maxmarkus** [sifue/vsc-surrounding#1]
Hello, 

Thanks for this great piece of software, helps alot. I wonder if it is possible to have the surrounding.json globally available in vscode, so I don't need to copy/paste it into every project workspace and keep it in sync manually. 
Local surrounding.json could also override globally defined ones, if necessary (not for me).

Best, Markus

**Comment by sifue** [comment]
Thanks for your idea. Global setting and override with local file, I'll try it.

**Comment by Joshdw** [comment]
+1 to this.

Furthermore, I'd just like to say, what an amazing snippet this is! I had to localize a lot of strings in a standard php project, so this was a complete life saver being able to quickly make a macro to add <?= _('textselection') ?> to hundreds of words.

**Comment by sifue** [comment]
I add  configuration of user setting with 7d28c98
Thanks your requests.

**Comment by sifue** [comment]
Now version 1.4.0 released. please update this extension.
